# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-iam-s3-user
  description: Terraform module to provision a basic IAM user with permissions to access S3 resources, e.g. to give the user read/write/delete access to the objects in an S3 bucket
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-modules, iam, s3, aws-credentials, cicd, circleci, travis-ci, codefresh




